name: Build and Publish Executables

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Executable with PyInstaller
        run: pyinstaller --onefile --windowed --icon="assets/icon.ico" --name "Printable_Notes_Generator" src/app_gui.py

      - name: Zip macOS App Bundle
        if: runner.os == 'macOS'
        run: |
          cd dist
          zip -r Printable_Notes_Generator_macOS.zip Printable_Notes_Generator.app

      - name: Publish Windows Release
        if: runner.os == 'Windows'
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          files: dist/Printable_Notes_Generator.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Mac Release
        if: runner.os == 'macOS'
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          files: dist/Printable_Notes_Generator_macOS.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
